# Generated by Django 3.1.5 on 2021-02-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_day',
        ),
    ]
