# Generated by Django 3.1.5 on 2021-02-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210213_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='bookmark_num',
            new_name='ebookmark_num',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='bookmark_users',
            new_name='ebookmark_users',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='bookmarked',
            new_name='ebookmarked',
        ),
    ]
