# Generated by Django 3.1.5 on 2021-02-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210213_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ebookmark_num',
            new_name='bookmark_num',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ebookmark_users',
            new_name='bookmark_users',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ebookmarked',
            new_name='bookmarked',
        ),
    ]
