# Generated by Django 3.1.7 on 2021-03-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_profile_my_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('content', models.TextField(default='', verbose_name='Content')),
                ('written_time', models.DateTimeField(auto_now=True)),
                ('ref_tags', models.TextField(default='', verbose_name='Ref Tags')),
                ('viewed_num', models.PositiveIntegerField(default=0)),
                ('solved', models.BooleanField(default='False')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='작성자')),
            ],
        ),
    ]
