# Generated by Django 3.1.7 on 2021-03-01 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tech',
            field=models.TextField(default='', verbose_name='Tech Stack'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(default='', max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.URLField(default='', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(default='', max_length=50, verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(default='', max_length=50, verbose_name='first name')),
                ('name2', models.CharField(default='', max_length=50, verbose_name='second name')),
                ('name3', models.CharField(default='', max_length=50, verbose_name='third name')),
                ('url1', models.URLField(default='', verbose_name='first url')),
                ('url2', models.URLField(default='', verbose_name='second url')),
                ('url3', models.URLField(default='', verbose_name='third url')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.project', verbose_name='링크 페이지'),
        ),
    ]
