# Generated by Django 3.1.7 on 2021-03-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210301_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_tags',
            field=models.TextField(default='', verbose_name='My Tags'),
        ),
    ]
