import {
  getAuthFromCookie,
  getUserIdFromCookie,
  getUserNicknameFromCookie,
  getUserMyTagsFromCookie,
} from '@/utils/cookies';

export default {
  id: getUserIdFromCookie() || '',
  token: getAuthFromCookie() || '',
  nickname: getUserNicknameFromCookie() || '',
  myTags: getUserMyTagsFromCookie() ? getUserMyTagsFromCookie() : [],
  liquidTagGuideModal: false,
  accountModal: false,
  accountModalType: 'login',
  follow: {
    modal: false,
    tab: 'follow',
    id: 0,
  },
  leftDrawal: true,
  tagFilter: false,
  selectedTags: [],
  tags_selected: {
    Angular: true,
    Backend: true,
    CSS3: true,
    Django: true,
    Docker: true,
    Frontend: true,
    HTML5: true,
    Java: true,
    JavaScript: true,
    MariaDB: true,
    MySQL: true,
    'Node.js': true,
    Python3: true,
    React: true,
    Spring: true,
    TypeScript: true,
    'Vue.js': true,
  },
  all_tag_list: [
    'Angular',
    'Backend',
    'CSS3',
    'Django',
    'Docker',
    'Frontend',
    'HTML5',
    'Java',
    'JavaScript',
    'MariaDB',
    'MySQL',
    'Node.js',
    'Python3',
    'React',
    'Spring',
    'TypeScript',
    'Vue.js',
  ],
};
