import {
  getAuthFromCookie,
  getUserIdFromCookie,
  getUserNicknameFromCookie,
} from '@/utils/cookies';

export default {
  id: getUserIdFromCookie() || '',
  token: getAuthFromCookie() || '',
  nickname: getUserNicknameFromCookie() || '',
  accountModal: false,
  accountModalType: 'login',
  follow: {
    modal: false,
    tab: 'follow',
  },
  leftDrawal: true,
  tagFilter: false,
  myTags: ['JavaScript', 'Vue.js', 'React', 'Python3'],
  selectedTags: [],
  tags_selected: {
    Angular: false,
    BackEnd: false,
    CSS3: false,
    Django: false,
    Docker: false,
    FrontEnd: false,
    HTML5: false,
    Java: false,
    JavaSscript: false,
    MariaDB: false,
    MySQL: false,
    'Node.js': false,
    Python3: false,
    React: false,
    Spring: false,
    Typescript: false,
    'Vue.js': false,
  },
  all_tag_list: [
    'JavaScript',
    'Vue.js',
    'Python3',
    'Backend',
    'Frontend',
    'Angular',
    'Django',
    'Java',
    'Typescript',
    'Docker',
    'React',
    'Frontend',
    'Backend',
    'Typescript',
    'Spring',
    'HTML5',
    'CSS3',
    'MySql',
    'MariaDB',
    'Node.js',
  ].sort(),
};
