# Generated by Django 3.1.5 on 2021-02-08 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail_img', models.ImageField(default='', upload_to='%Y/%m/%d')),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('Python3', 'Python3'), ('Django', 'Django'), ('Java', 'Java'), ('Spring', 'Spring'), ('HTML5', 'HTML5'), ('CSS3', 'CSS3'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('Vue.js', 'Vue.js'), ('React', 'React'), ('Angular', 'Angular'), ('Node.js', 'Node.js'), ('Swift', 'Swift'), ('Ruby', 'Ruby'), ('Ruby on Rails', 'Ruby on Rails'), ('MySQL', 'MySQL'), ('MariaDB', 'MariaDB'), ('MongoDB', 'MongoDB'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('FrontEnd', 'FrontEnd'), ('BackEnd', 'BackEnd'), ('DevOps', 'DevOps'), ('Artificial Intelligence', 'Artificial Intelligence'), ('BigData', 'BigData'), ('Blockchain', 'Blockchain'), ('Internet of Things', 'Internet of Things'), ('Augmented Reality', 'Augmented Reality'), ('Virtual Reality', 'Virtual Reality')], max_length=273)),
                ('like_num', models.PositiveIntegerField(default=0)),
                ('liked', models.BooleanField(default='False')),
                ('bookmark_num', models.PositiveIntegerField(default=0)),
                ('bookmarked', models.BooleanField(default='False')),
                ('viewed_num', models.PositiveIntegerField(default=0)),
                ('written_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('profile_img', models.ImageField(default='', upload_to='%Y/%m/%d')),
                ('pinned_num', models.PositiveIntegerField(default=0)),
                ('pinned_post', models.BooleanField(default='False')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bookmark_users', models.ManyToManyField(blank=True, related_name='bookmark_articles', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_articles', to=settings.AUTH_USER_MODEL)),
                ('pinned_users', models.ManyToManyField(related_name='pinned_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('profile_img', models.ImageField(default='', upload_to='%Y/%m/%d')),
                ('written_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_profile_title', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
