# Generated by Django 3.1.1 on 2021-02-03 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail_img', models.ImageField(default='', upload_to='%Y/%m/%d')),
                ('ref_tags', multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python3'), ('JV', 'Java'), ('HT', 'HTML5'), ('CS', 'CSS3'), ('JS', 'JavaScript'), ('VU', 'Vue.js'), ('RE', 'React.js'), ('AN', 'Angular'), ('MY', 'MySQL'), ('MD', 'MariaDB')], max_length=29)),
                ('like_num', models.PositiveIntegerField(default=0)),
                ('liked', models.BooleanField(default='True')),
                ('bookmark_num', models.PositiveIntegerField(default=0)),
                ('bookmarked', models.BooleanField(default='True')),
                ('viewed_num', models.PositiveIntegerField(default=0)),
                ('written_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('profile_img', models.ImageField(default='', upload_to='%Y/%m/%d')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bookmark_users', models.ManyToManyField(related_name='bookmark_articles', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('profile_img', models.ImageField(default='', upload_to='%Y/%m/%d')),
                ('written_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
