# Generated by Django 3.1.5 on 2021-02-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ref_tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='username',
        ),
    ]
