# Generated by Django 3.1.5 on 2021-02-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnaValidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qna_image', models.ImageField(upload_to='image_qna/%Y/%m/%d')),
                ('qna_url', models.URLField()),
            ],
        ),
    ]
