# Generated by Django 3.1.5 on 2021-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsValidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_image', models.ImageField(upload_to='image_ans/%Y/%m/%d')),
                ('ans_url', models.URLField()),
            ],
        ),
    ]
