# Generated by Django 3.1.5 on 2021-02-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
