# Generated by Django 3.1.5 on 2021-02-03 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('assisted', models.BooleanField(default='False')),
                ('like_ans_num', models.PositiveIntegerField(default=0)),
                ('liked_ans', models.BooleanField(default='False')),
                ('written_time', models.DateTimeField(auto_now_add=True)),
                ('like_ans_users', models.ManyToManyField(related_name='like_anss', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('ref_tags', multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python3'), ('JV', 'Java'), ('HT', 'HTML5'), ('CS', 'CSS3'), ('JS', 'JavaScript'), ('VU', 'Vue.js'), ('RE', 'React.js'), ('AN', 'Angular'), ('MY', 'MySQL'), ('MD', 'MariaDB')], max_length=29)),
                ('like_num', models.PositiveIntegerField(default=0)),
                ('comment_num', models.PositiveIntegerField(default=0)),
                ('liked', models.BooleanField(default='False')),
                ('bookmark_num', models.PositiveIntegerField(default=0)),
                ('bookmarked', models.BooleanField(default='False')),
                ('solved', models.BooleanField(default='False')),
                ('viewed_num', models.PositiveIntegerField(default=0)),
                ('written_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('bookmark_users', models.ManyToManyField(related_name='bookmark_qnas', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(related_name='like_qnas', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Qnasmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('username', models.CharField(default='', max_length=30)),
                ('written_time', models.DateTimeField(auto_now_add=True)),
                ('qna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnas.qna')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anssmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('username', models.CharField(default='', max_length=30)),
                ('written_time', models.DateTimeField(auto_now_add=True)),
                ('ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnas.ans')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ans',
            name='qna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnas.qna'),
        ),
    ]
