# Generated by Django 3.1.5 on 2021-02-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='is_following',
            field=models.BooleanField(default='False'),
        ),
    ]
