# Generated by Django 3.1.5 on 2021-02-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0002_imagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaImageURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_url', models.URLField(blank=True, max_length=400, verbose_name='URL')),
                ('image_file', models.ImageField(blank=True, upload_to='qna', verbose_name='Image')),
            ],
        ),
    ]
