# Generated by Django 3.1.5 on 2021-02-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0002_auto_20210205_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anssmall',
            old_name='userid',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='anssmall',
            name='username',
        ),
        migrations.AlterField(
            model_name='ans',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='qna',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
