# Generated by Django 3.1.5 on 2021-02-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0003_qnaimageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='file_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
