# Generated by Django 3.1.5 on 2021-02-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0003_auto_20210207_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='img',
            field=models.ImageField(default='', upload_to='%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='qna',
            name='img',
            field=models.ImageField(default='', upload_to='%Y/%m/%d'),
        ),
    ]
