# Generated by Django 3.1.5 on 2021-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0004_imagefile_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='post_file',
            field=models.FileField(upload_to='qna'),
        ),
    ]
