# Generated by Django 3.1.5 on 2021-02-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0006_auto_20210214_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
