# Generated by Django 3.1.5 on 2021-02-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0007_auto_20210214_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='qna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qna_image', to='qnas.qna'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='img_file',
            field=models.ImageField(upload_to='qna'),
        ),
    ]
