# Generated by Django 3.1.5 on 2021-02-05 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('qnas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_userinfo', to='profiles.profile'),
        ),
    ]
