# Generated by Django 3.1.1 on 2021-02-03 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('profile_img', imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to='accounts/images')),
                ('region', models.CharField(blank=True, choices=[('SEL', '서울'), ('PUS', '부산'), ('TAE', '대구'), ('INC', '인천'), ('KWJ', '광주'), ('TAJ', '대전'), ('USN', '울산'), ('KYG', '경기'), ('KAW', '강원'), ('CCB', '충북'), ('CCN', '충남'), ('CLB', '전북'), ('CLN', '전남'), ('KSB', '경북'), ('KSN', '경남'), ('CHJ', '제주')], max_length=4)),
                ('group', models.CharField(blank=True, default='', max_length=40)),
                ('bio', models.TextField(blank=True, default='')),
                ('sns_name', models.TextField(blank=True, default='')),
                ('sns_url', models.CharField(blank=True, default='', max_length=100)),
                ('tech_stack', multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python3'), ('DJ', 'Django'), ('JV', 'Java'), ('SP', 'Spring'), ('HT', 'HTML5'), ('CS', 'CSS3'), ('JS', 'JavaScript'), ('VU', 'Vue.js'), ('RE', 'React'), ('AN', 'Angular'), ('NO', 'Node.js'), ('RU', 'Ruby'), ('RO', 'Ruby on Rails'), ('MY', 'MySQL'), ('MD', 'MariaDB'), ('MB', 'MongoDB'), ('DK', 'Docker'), ('KN', 'Kubernetes')], max_length=53)),
                ('project_name', models.CharField(blank=True, default='', max_length=100)),
                ('project_url', models.CharField(blank=True, default='', max_length=100)),
                ('tag', multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python3'), ('DJ', 'Django'), ('JV', 'Java'), ('SP', 'Spring'), ('HT', 'HTML5'), ('CS', 'CSS3'), ('JS', 'JavaScript'), ('VU', 'Vue.js'), ('RE', 'React'), ('AN', 'Angular'), ('NO', 'Node.js'), ('RU', 'Ruby'), ('RO', 'Ruby on Rails'), ('MY', 'MySQL'), ('MD', 'MariaDB'), ('MB', 'MongoDB'), ('DK', 'Docker'), ('KN', 'Kubernetes'), ('FE', 'FrontEnd'), ('BE', 'BackEnd'), ('DO', 'DevOps'), ('AI', 'Artificial Intelligence'), ('BD', 'BigData'), ('BC', 'Blockchain'), ('IT', 'Internet of Things'), ('AR', 'Augmented Reality'), ('VR', 'Virtual Reality')], max_length=80)),
                ('comments', models.ManyToManyField(related_name='profile_comments', to='articles.Comment')),
                ('pinned_posts', models.ManyToManyField(related_name='profile_pinned_posts', to='articles.Article')),
                ('posts', models.ManyToManyField(related_name='profile_posts', to='articles.Article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
