# Generated by Django 3.1.5 on 2021-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
